### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by aurelian2** [avcado/desparity#3]
Hey avcado

firstly, is this finally your magnum opus? your final OS? or will this be like the others that you have abandoned?

secondly, why are you using bare bones from the OSDev wiki? it is an outdated base of an OS that uses bad practices and uses GRUB, when you could be using [limine](https://github.com/limine-bootloader/limine) instead, a x86_64 bootloader that drop you right into 64-bit long mode, and gives you very useful information such as ACPI information (which mb1 does not provide).

thirdly, you shouldn't be using the VGA textmode buffer; you ought to have been using the VESA framebuffer mode instead, which provides you with something that is far more extensible and can do actually good graphics, instead of pure text printing or color filling. 

fourthly, as a reccomendation, your kernel should operate in the higher half of memory, as most compilers will almost always assume that userspace programs will be in the lower half of memory, and having a userspace program "collide" with the kernel in the virtual address space is never a good idea.

**Comment by avcado** [comment]
i havent worked on this since march so probably abandoned

**Comment by rizet** [comment]
This entire project is a hot mess.

**Comment by avcado** [comment]
holy shit no way

**Comment by rizet** [comment]
What?

**Comment by avcado** [comment]
No.
